### ISSUE TITLE
WISH: Add BugReports: https://github.com/jcrodriguez1989/MIGSA/issues

### ISSUE THREAD

**Issue by HenrikBengtsson** [jcrodriguez1989/MIGSA#1]
Hi, it was a bit hard to find this repos from http://www.bioconductor.org/packages/release/bioc/html/MIGSA.html.  Would you mind adding:

```
BugReports: https://github.com/jcrodriguez1989/MIGSA/issues
```

to your DESCRIPTION file?  And/or, possible append

```
URL: https://jcrodriguez.rbind.io/, https://github.com/jcrodriguez1989/MIGSA
```

**Comment by jcrodriguez1989** [comment]
Hi @HenrikBengtsson ,
thanks for noting and creating these issues. I had this package almost orphaned.
I have fixed your suggestions and added some other edits.
Thanks!
