### ISSUE TITLE
Add RUnit to Suggests:

### ISSUE THREAD

**Issue by HenrikBengtsson** [jcrodriguez1989/MIGSA#2]
Please consider adding **RUnit** to `Suggests:`.

When running reverse-dependency checks on my **matrixStats** package, I get an error on **MIGSA**;

```
      Error in library("RUnit", quietly = TRUE) : 
        there is no package called 'RUnit'
```

This is not new, this error has been there for many years. 

You should be able to reproduce this error locally if you run `R CMD check --as-cran ...` on MIGSA.  It requires that `--as-cran` option, which makes sure the package tests are run in a sandboxed environment.   The most likely reason why you, or Bioconductor, don't get this error is that you run without that option.  In that case, `R CMD check` will fallback and look **RUnit** in your personal package library.

**Comment by jcrodriguez1989** [comment]
Hi @HenrikBengtsson ,
thanks for noting and creating these issues. I had this package almost orphaned.
I have fixed your suggestions and added some other edits.
Thanks!
