### ISSUE TITLE
Error: 'length(x) = 2 > 1' in coercion to 'logical(1)'

### ISSUE THREAD

**Issue by HenrikBengtsson** [jcrodriguez1989/MIGSA#3]
Hi (again).  You've got a bug of the type 

```r
> x <- 1:2
> if (x == 1) message("x == 1")
x == 1
Warning message:
In if (x == 1) message("x == 1") :
  the condition has length > 1 and only the first element will be used
```

This is described in https://github.com/HenrikBengtsson/Wishlist-for-R/issues/38 and https://developer.r-project.org/Blog/public/2018/10/12/conditions-of-length-greater-than-one/index.html.  R will at some point turn this warning into a run-time error.

I spotted this when running reverse-depency checks of **matrixStats**.  You can replicated this error locally by testing your packages with `R CMD check --as-cran`:

```
*   checking running R code from vignettes ...
    ```
      ‘MIGSA.Rnw’ using ‘UTF-8’... failed
      ‘gettingPbcmcData.Rnw’ using ‘UTF-8’... OK
      ‘gettingTcgaData.Rnw’ using ‘UTF-8’... OK
     ERROR
    Errors in running code in vignettes:
    when running code in ‘MIGSA.Rnw’
      ...
            term        minHeight allParents
    target  "character" "logical" "list"    
    defined "character" "logical" "list"    
     --- function search by body ---
    S4 Method getHeight:MIGSA defined in namespace MIGSA with signature character#logical#list has this body.
     ----------- END OF FAILURE REPORT -------------- 
    
      When sourcing ‘MIGSA.R’:
    Error: 'length(x) = 2 > 1' in coercion to 'logical(1)'
    Execution halted
    ```
```

**Comment by jcrodriguez1989** [comment]
Hi @HenrikBengtsson ,
thanks for noting and creating these issues. I had this package almost orphaned.
I have fixed your suggestions and added some other edits.
MIGSA is now successfully passing `R CMD check --as-cran ...`.
However, I have noted some other issues I am currently working on.
Thanks!
